// Fixture driven conformance tests over the JSON fixtures in testdata/fixtures, generated by scripts/generate-fixtures.ts from the prosemirror-model TypeScript
// sources. The fixture format and the assertions made here are defined in the PORTING.md section "Fixtures".

package model //nolint:testpackage

import (
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"sync"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"gitlab.com/tozd/go/errors"
	"gitlab.com/tozd/go/x"
)

// Named validators referenced by the example schema, with the semantics fixed in the PORTING.md section "Schema JSON dialect". Non-string values are always
// invalid for both.
var (
	fixtureLinkURLRegexp     = regexp.MustCompile(`(?i)^(?:/(?:[^/]|$)|https?://[^/]|mailto:[^/])`)
	fixtureResourceURLRegexp = regexp.MustCompile(`(?i)^(?:/(?:[^/]|$)|https?://[^/])`)
)

func fixtureURLValidator(name string, pattern *regexp.Regexp) AttrValidator {
	return func(value any) errors.E {
		s, ok := value.(string)
		if !ok {
			return errors.Errorf("%s: value is not a string", name)
		}
		if !pattern.MatchString(s) {
			return errors.Errorf("%s: invalid value: %s", name, s)
		}
		return nil
	}
}

// fixtureValidators returns the validator registry passed to every fixture schema. The example schema references both names, the other schemas
// reference neither.
func fixtureValidators() map[string]AttrValidator {
	return map[string]AttrValidator{
		"linkURL":     fixtureURLValidator("linkURL", fixtureLinkURLRegexp),
		"resourceURL": fixtureURLValidator("resourceURL", fixtureResourceURLRegexp),
	}
}

var (
	fixtureSchemasMu sync.Mutex             //nolint:gochecknoglobals
	fixtureSchemas   = map[string]*Schema{} //nolint:gochecknoglobals
)

// fixtureSchema compiles the schema stored at testdata/<name>, caching compiled schemas so that each schema is compiled once for the whole test binary.
func fixtureSchema(t *testing.T, name string) *Schema {
	t.Helper()
	fixtureSchemasMu.Lock()
	defer fixtureSchemasMu.Unlock()
	if s, ok := fixtureSchemas[name]; ok {
		return s
	}
	specJSON, err := os.ReadFile(filepath.Join("testdata", name)) //nolint:gosec
	require.NoError(t, err)
	s, errE := NewSchema(specJSON, fixtureValidators())
	require.NoError(t, errE, "% -+#.1v", errE)
	fixtureSchemas[name] = s
	return s
}

type fixtureCase struct {
	Name        string          `json:"name"`
	Input       string          `json:"input"`
	Doc         json.RawMessage `json:"doc"`
	Canonical   string          `json:"canonical"`
	Recanonical *string         `json:"recanonical"`
}

type fixtureFile struct {
	Schema string         `json:"schema"`
	Cases  []*fixtureCase `json:"cases"`
}

type fixtureEntry struct {
	Name string
	File *fixtureFile
}

// loadFixtureFiles reads every fixture file under testdata/fixtures. Decoding is strict so that any drift in the fixture format fails the suite instead of
// being silently ignored.
func loadFixtureFiles(t *testing.T) []fixtureEntry {
	t.Helper()
	paths, err := filepath.Glob(filepath.Join("testdata", "fixtures", "*.json"))
	require.NoError(t, err)
	require.NotEmpty(t, paths, "no fixture files found")
	entries := make([]fixtureEntry, 0, len(paths))
	for _, path := range paths {
		data, err := os.ReadFile(path) //nolint:gosec
		require.NoError(t, err, path)
		var file fixtureFile
		errE := x.DecodeJSONWithoutUnknownFields(bytes.NewReader(data), &file)
		require.NoError(t, errE, "%s: % -+#.1v", path, errE)
		require.NotEmpty(t, file.Schema, path)
		require.NotEmpty(t, file.Cases, path)
		entries = append(entries, fixtureEntry{Name: strings.TrimSuffix(filepath.Base(path), ".json"), File: &file})
	}
	return entries
}

// TestFixtures asserts the per case contract from the PORTING.md section "Fixtures": parsing the input yields the recorded document, serializing that document
// yields the recorded canonical HTML, and the canonical HTML re-canonicalizes to itself exactly when no "recanonical" value is recorded (to the recorded
// "recanonical" value otherwise).
func TestFixtures(t *testing.T) {
	t.Parallel()
	for _, entry := range loadFixtureFiles(t) {
		schema := fixtureSchema(t, entry.File.Schema)
		t.Run(entry.Name, func(t *testing.T) {
			t.Parallel()
			for _, c := range entry.File.Cases {
				t.Run(c.Name, func(t *testing.T) {
					t.Parallel()
					parsed, errE := ParseHTML(schema, c.Input, ParseOptions{})
					require.NoError(t, errE, "% -+#.1v", errE)

					parsedJSON, errE := x.MarshalWithoutEscapeHTML(parsed)
					require.NoError(t, errE, "% -+#.1v", errE)
					assert.JSONEq(t, string(c.Doc), string(parsedJSON))

					assert.Equal(t, c.Canonical, SerializeHTML(parsed))

					recanonicalized, errE := CanonicalizeHTML(schema, c.Canonical, ParseOptions{})
					require.NoError(t, errE, "% -+#.1v", errE)
					if c.Recanonical != nil {
						assert.Equal(t, *c.Recanonical, recanonicalized)
					} else {
						assert.Equal(t, c.Canonical, recanonicalized)
					}

					isCanonical, errE := IsCanonicalHTML(schema, c.Canonical, ParseOptions{})
					require.NoError(t, errE, "% -+#.1v", errE)
					assert.Equal(t, c.Recanonical == nil, isCanonical)
				})
			}
		})
	}
}

// TestFixtureProperties checks properties which must hold for every fixture document: the recorded document JSON deserializes through Schema.NodeFromJSON
// (which runs a full Check) into a document equal to the parsed one, that document serializes to the recorded canonical HTML and marshals back to the recorded
// JSON, and canonicalization of the serialization of the parsed document reaches a fixed point (immediately, or after the recorded "recanonical" step).
func TestFixtureProperties(t *testing.T) {
	t.Parallel()
	for _, entry := range loadFixtureFiles(t) {
		schema := fixtureSchema(t, entry.File.Schema)
		t.Run(entry.Name, func(t *testing.T) {
			t.Parallel()
			for _, c := range entry.File.Cases {
				t.Run(c.Name, func(t *testing.T) {
					t.Parallel()
					parsed, errE := ParseHTML(schema, c.Input, ParseOptions{})
					require.NoError(t, errE, "% -+#.1v", errE)

					doc2, errE := schema.NodeFromJSON(c.Doc)
					require.NoError(t, errE, "% -+#.1v", errE)
					assert.True(t, doc2.Eq(parsed), "deserialized document does not equal parsed document")

					assert.Equal(t, c.Canonical, SerializeHTML(doc2))

					doc2JSON, errE := x.MarshalWithoutEscapeHTML(doc2)
					require.NoError(t, errE, "% -+#.1v", errE)
					assert.JSONEq(t, string(c.Doc), string(doc2JSON))

					reparsed, errE := ParseHTML(schema, SerializeHTML(parsed), ParseOptions{})
					require.NoError(t, errE, "% -+#.1v", errE)
					reserialized := SerializeHTML(reparsed)
					if c.Recanonical != nil {
						assert.Equal(t, *c.Recanonical, reserialized)
					}
					recanonicalized, errE := CanonicalizeHTML(schema, reserialized, ParseOptions{})
					require.NoError(t, errE, "% -+#.1v", errE)
					assert.Equal(t, reserialized, recanonicalized, "canonicalization fixed point not reached")
				})
			}
		})
	}
}
